<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
	name="mobile-robot-obstacle">

  <!-- properties -->
  <property name="table_height" value="0.7" />
  <property name="table_width" value="1.0" />
  <property name="table_depth" value="1.0" />
  <property name="leg_radius" value="0.02" />
  <property name="table_x" value="2" />
  <property name="table_y" value="0.0" />
  <property name="table_z" value="0.0" />


  <property name="table_top_thickness" value="0.05"/>

  <property name="M_PI" value="3.1415926535897931" />

  <xacro:include filename="$(find araig_gazebo_worlds)/urdf/common.xacro" />
  <xacro:include filename="$(find araig_gazebo_worlds)/urdf/materials.urdf.xacro" />


  <xacro:macro name="new_box" params="new_box_name box_width box_length box_height material parent *origin">
    <link name="box_${new_box_name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
	      <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </visual>
      <!-- <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
  	  <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </collision> -->
    <inertial>
      <mass value="1.0" />
      <origin xyz="${table_x} ${table_y} ${table_z+table_height-table_top_thickness/2}" />
      <inertia ixx="1" ixy="0"  ixz="0"
               iyy="1" iyz="0"
               izz="1" />
    </inertial> 
    </link>
    <gazebo reference="box_${new_box_name}">
      <material>${material}</material>
    </gazebo>
    <joint name="joint_box_${new_box_name}" type="fixed">
       <xacro:insert_block name="origin"/>
       <parent link="${parent}"/>
       <child link="box_${new_box_name}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="new_cylinder" params="new_cylinder_name cylinder_diameter cylinder_height material parent *origin pose">
    <link name="cylinder_${new_cylinder_name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
              <cylinder length="${cylinder_height}" radius="${cylinder_diameter/2}"/>
        </geometry>
      </visual>
      <!-- <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
  	  <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </collision> -->
      <xacro:default_inertial/>
    </link>
    <gazebo reference="cylinder_${new_cylinder_name}">
      <material>${material}</material>
	<light name='cylinder_${new_cylinder_name}/light_source1' type='spot'>
		  <pose>${pose}</pose>
		  <attenuation>
		    <range>40</range>
		    <linear>0.05</linear>
		    <constant>-0.2</constant>
		  </attenuation>
		  <diffuse>0 1 0 1</diffuse>
		  <specular>0 1 0 1</specular>
		  <spot>
		    <inner_angle>0.3</inner_angle>
		    <outer_angle>0.35</outer_angle>
		    <falloff>1</falloff>
		  </spot>
	</light>
	  <plugin name='light_control' filename='libFlashLightPlugin.so'>
	      <enable>true</enable>
	      <light>
		<id>'cylinder_${new_cylinder_name}'/light_source1</id>
		<duration>0.5</duration>
		<interval>0.5</interval>
		<color>1 1 1</color>
	      </light>
	   </plugin>
	  <selfCollide>false</selfCollide>
    </gazebo>
    <joint name="joint_box_${new_cylinder_name}" type="fixed">
       <xacro:insert_block name="origin"/>
       <parent link="${parent}"/>
       <child link="cylinder_${new_cylinder_name}"/>
    </joint>
  </xacro:macro>

  <!-- world link -->
  <link name="world" />


  <xacro:new_cylinder new_cylinder_name="light_1" cylinder_height ="2.25" cylinder_diameter="0.1"  material="experiments/wall" parent="box_table_top" pose="0 1 1.2 -0.55 0.1 0">
  <origin xyz="0 1 0" rpy="0 0 0"/>
  </xacro:new_cylinder>

  <xacro:new_cylinder new_cylinder_name="light_2" cylinder_height ="2.25" cylinder_diameter="0.1"  material="experiments/wall" parent="box_table_top" pose="0 -1 1.2  0.55 0.1 0">
  <origin xyz="0 -1 0" rpy="0 0 0"/>
  </xacro:new_cylinder>

   <!-- table top -->
  <xacro:new_box new_box_name="table_top" box_width ="${table_width}" box_length="${table_depth}" box_height="${table_top_thickness}" material="experiments/woodfloor" parent="world">
  <origin xyz="${table_x} ${table_y} ${table_z+table_height-table_top_thickness/2}" rpy="0 0 0"/>
  </xacro:new_box>

<joint name="leg1_joint" type="fixed" >
    <parent link="world" />
    <origin xyz="${table_x+table_width/2} ${table_y+table_depth/2} ${table_z+table_height}" rpy="0 0 0" />
    <child link="leg1_link" />
  </joint> 
  <link name="leg1_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-table_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${-table_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${table_height}" />
      </geometry>
    </visual> 
  </link>
  <gazebo reference="leg1_link">
    <material>Gazebo/Red</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="leg2_joint" type="fixed" >
    <parent link="world" />
    <origin xyz="${table_x-table_width/2} ${table_y+table_depth/2} ${table_z+table_height}" rpy="0 0 0" />
    <child link="leg2_link" />
  </joint> 
  <link name="leg2_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-table_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${-table_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${table_height}" />
      </geometry>
    </visual> 
  </link>
  <gazebo reference="leg2_link">
    <material>Gazebo/Red</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="leg3_joint" type="fixed" >
    <parent link="world" />
    <origin xyz="${table_x+table_width/2} ${table_y-table_depth/2} ${table_z+table_height}" rpy="0 0 0" />
    <child link="leg3_link" />
  </joint> 
  <link name="leg3_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-table_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${-table_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${table_height}" />
      </geometry>
    </visual> 
  </link>
  <gazebo reference="leg3_link">
    <material>Gazebo/Red</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="leg4_joint" type="fixed" >
    <parent link="world" />
    <origin xyz="${table_x-table_width/2} ${table_y-table_depth/2} ${table_z+table_height}" rpy="0 0 0" />
    <child link="leg4_link" />
  </joint> 
  <link name="leg4_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-table_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${-table_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${table_height}" />
      </geometry>
    </visual> 
  </link>
  <gazebo reference="leg4_link">
    <material>Gazebo/Red</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>
  <gazebo>
    <static>true</static>
    <canonicalBody>world</canonicalBody>
  </gazebo>

</robot>
