<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
	name="mobile-robot-obstacle">

  <!-- properties -->
  <xacro:property name="belt_width" value="0.4" />
  <xacro:property name="belt_length" value="250" />
  <xacro:property name="belt_height" value="0.1" />
  <xacro:property name="belt_mass" value="5.0" />

  <xacro:property name="move_obstacle_width" value="0.3" />
  <xacro:property name="move_obstacle_length" value="0.3" />
  <xacro:property name="move_obstacle_height" value="0.4" />
  <xacro:property name="move_obstacle_mass" value="1" />

  <xacro:property name="move_obstacle_distance" value="4"/>
  <xacro:property name="world_to_belt_offset_height" value="10" />

  <xacro:include filename="$(find araig_gazebo_worlds)/urdf/common.xacro" />
  <xacro:include filename="$(find araig_gazebo_worlds)/urdf/materials.urdf.xacro" />

  <!-- macros -->
  <xacro:macro name="box_inertial" params="x y z mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
          iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0"
          izz="${0.0833333 * mass * (x*x + y*y)}" />
    </inertial>
  </xacro:macro>

<geometry>
    <cylinder length="1.2" radius="1"/>
</geometry>

  <xacro:macro name="new_cylinder" params="new_cylinder_name cylinder_diameter cylinder_height material parent *origin">
    <link name="cylinder_${new_cylinder_name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
              <cylinder length="${cylinder_height}" radius="${cylinder_diameter/2}"/>
        </geometry>
      </visual>
      <!-- <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
  	  <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </collision> -->
      <xacro:default_inertial/>
    </link>
    <gazebo reference="cylinder_${new_cylinder_name}">
      <material>${material}</material>
    </gazebo>
    <joint name="joint_box_${new_cylinder_name}" type="fixed">
       <xacro:insert_block name="origin"/>
       <parent link="${parent}"/>
       <child link="cylinder_${new_cylinder_name}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="new_box" params="new_box_name box_width box_length box_height material parent *origin">
    <link name="box_${new_box_name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
	      <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </visual>
      <!-- <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
  	  <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </collision> -->
      <xacro:default_inertial/>
    </link>
    <gazebo reference="box_${new_box_name}">
      <material>${material}</material>
    </gazebo>
    <joint name="joint_box_${new_box_name}" type="fixed">
       <xacro:insert_block name="origin"/>
       <parent link="${parent}"/>
       <child link="box_${new_box_name}"/>
    </joint>
  </xacro:macro>

   <xacro:macro name="new_box_collision" params="new_box_name box_width box_length box_height material parent *origin">
    <link name="box_${new_box_name}_collision">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
	      <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
  	  <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </collision>
      <xacro:default_inertial/>
    </link>
    <gazebo reference="box_${new_box_name}_collision">
      <material>${material}</material>
    </gazebo>
    <joint name="joint_box_${new_box_name}_collision" type="fixed">
       <xacro:insert_block name="origin"/>
       <parent link="${parent}"/>
       <child link="box_${new_box_name}_collision"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="move_obstacle" params="move_obstacle_num">
    <link name="move_obstacle_${move_obstacle_num}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
	  <box size="${move_obstacle_width} ${move_obstacle_length} ${move_obstacle_height}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
  	  <box size="${move_obstacle_width} ${move_obstacle_length} ${move_obstacle_height}"/>
        </geometry>
      </collision>
      <xacro:default_inertial/>
    </link>
    <gazebo reference="move_obstacle_${move_obstacle_num}">
      <material>Gazebo/Grey</material>
    </gazebo>
    <joint name="belt_to_move_obstacle_${move_obstacle_num}" type="fixed">
       <origin xyz="0 ${move_obstacle_num*(move_obstacle_length + move_obstacle_distance)-belt_length/3} ${move_obstacle_height/2-world_to_belt_offset_height-belt_height}"/>
       <parent link="my_belt"/>
       <child link="move_obstacle_${move_obstacle_num}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="camera_sensor" params="xyz rpy parent camera_suffix">
          <joint name="camera_${camera_suffix}_joint" type="fixed">
              <axis xyz="0 1 0" />
              <origin xyz="${xyz}" rpy="${rpy}"/>
              <parent link="${parent}"/>
              <child link="camera_${camera_suffix}_link"/>
          </joint>
          
          <link name="camera_${camera_suffix}_link">
              <collision>
                  <origin xyz="0 0 0" rpy="0 0 0"/>
                  <geometry>
                      <box size="0.02 0.08 0.05"/>
                  </geometry>
              </collision>
              <visual>
                  <origin xyz="0 0 0" rpy="0 0 0"/>
                  <geometry>
                      <box size="0.02 0.08 0.05"/>
                  </geometry>
                   <material name="grey" />
              </visual>
              <inertial>
                  <mass value="0.0001" />
                  <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
                  <inertia ixx="0.0000001" ixy="0" ixz="0" iyy="0.0000001" iyz="0" izz="0.0000001" />
              </inertial>
          </link>
          <gazebo reference="camera_${camera_suffix}_link">
              <sensor type="camera" name="camera">
                  <update_rate>30.0</update_rate>
                  <camera name="head">
                      <horizontal_fov>1.3962634</horizontal_fov>
                      <image>
                          <width>800</width>
                          <height>600</height>
                          <format>R8G8B8</format>
                      </image>
                      <clip>
                          <near>0.02</near>
                          <far>300</far>
                      </clip>
                      <noise>
                          <type>gaussian</type>
                          <mean>0.0</mean>
                          <stddev>0.007</stddev>
                      </noise>
                  </camera>
                  <plugin name="camera_${camera_suffix}_controller" filename="libgazebo_ros_camera.so">
                      <alwaysOn>true</alwaysOn>
                      <updateRate>30</updateRate>
                      <cameraName>camera_${camera_suffix}</cameraName>
                      <imageTopicName>image_raw</imageTopicName>
                      <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                      <frameName>camera_${camera_suffix}_link</frameName>
                      <hackBaseline>0.0</hackBaseline>
                      <distortionK1>0.0</distortionK1>
                      <distortionK2>0.0</distortionK2>
                      <distortionK3>0.0</distortionK3>
                      <distortionT1>0.0</distortionT1>
                      <distortionT2>0.0</distortionT2>
                  </plugin>
              </sensor>
      </gazebo>     
  </xacro:macro>

  <!-- gazebo plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>world</robotNamespace>
      <robotParam>/world_description</robotParam>
    </plugin>
  </gazebo>

  <!-- world link -->
  <link name="world" />


  <!-- moving belt link-->
  <link name="my_belt">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${belt_width} ${belt_length} ${belt_height}" />
      </geometry>
    </visual>
    <!-- <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${belt_width} ${belt_length} ${belt_height}" />
      </geometry>
    </collision> -->
    <xacro:box_inertial x="${belt_width}" y="${belt_length}" z="${belt_height}" mass="${belt_mass}">
	<origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:box_inertial>
  </link>
  <gazebo reference="my_belt">
    <material>Gazebo/WoodFloor</material>
  </gazebo>
  <joint name="floor_to_belt" type="prismatic">
    <parent link="world"/>
    <child link="my_belt"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/> 
    <origin xyz="${3 +belt_width/2} 0 ${belt_height + world_to_belt_offset_height}"/>
    <limit lower="100000" upper="-100000" velocity="5" effort="10"/>
  </joint>

  <!--move obstcals-->
  <xacro:move_obstacle move_obstacle_num="1"/>
  <xacro:move_obstacle move_obstacle_num="2"/>
  <xacro:move_obstacle move_obstacle_num="3"/>
  <xacro:move_obstacle move_obstacle_num="4"/>
  <xacro:move_obstacle move_obstacle_num="5"/>
  <xacro:move_obstacle move_obstacle_num="6"/>
  <xacro:move_obstacle move_obstacle_num="7"/>
  <xacro:move_obstacle move_obstacle_num="8"/>
  <xacro:move_obstacle move_obstacle_num="9"/>
  <xacro:move_obstacle move_obstacle_num="10"/>
  <xacro:move_obstacle move_obstacle_num="11"/>
  <xacro:move_obstacle move_obstacle_num="12"/>
  <xacro:move_obstacle move_obstacle_num="13"/>
  <xacro:move_obstacle move_obstacle_num="14"/>
  <xacro:move_obstacle move_obstacle_num="15"/>
  <xacro:move_obstacle move_obstacle_num="16"/>
  <xacro:move_obstacle move_obstacle_num="17"/>

<!--world objects-->

   <!-- wall short side -->
  <xacro:new_box new_box_name="wall_short_1" box_width ="1" box_length="0.1" box_height="0.5" material="experiments/wall" parent="world">
  <origin xyz="5 1.55 -0.05" rpy="0 0 0"/>
  </xacro:new_box>


   <!-- wall short side -->
  <xacro:new_box new_box_name="wall_short_2" box_width ="1" box_length="0.1" box_height="0.5" material="experiments/wall" parent="world">
  <origin xyz="5 -1.55 -0.05" rpy="0 0 0"/>
  </xacro:new_box>



   <!-- normal floor link -->
  <xacro:new_box new_box_name="normal_floor_square" box_width ="2" box_length="2" box_height="0.1" material="experiments/normalfloor" parent="world">
  <origin xyz="3 0 -0.05" rpy="0 0 0"/>
  </xacro:new_box>

  <!-- wood floor square link -->
  <xacro:new_box new_box_name="wood_floor_square_1" box_width ="2" box_length="2" box_height="0.1" material="experiments/woodfloor" parent="world">
  <origin xyz="1 0 -0.05" rpy="0 0 0"/>
  </xacro:new_box>

  <!-- wood floor square link -->
  <xacro:new_box new_box_name="wood_floor_square_2" box_width ="2" box_length="2" box_height="0.1" material="experiments/woodfloor" parent="world">
  <origin xyz="5 0 -0.05" rpy="0 0 0"/>
  </xacro:new_box>

   <!-- wall long side -->
  <xacro:new_box new_box_name="wall_long_1" box_width ="0.1" box_length="4" box_height="0.5" material="experiments/wall" parent="world">
  <origin xyz="3 2.05 -0.05" rpy="0 0 0"/>
  </xacro:new_box>

  <!-- wood floor rectangle link -->
  <xacro:new_box new_box_name="wood_floor_rectangle_1" box_width ="1" box_length="4" box_height="0.1" material="experiments/woodfloor" parent="world">
  <origin xyz="3 1.5 -0.05" rpy="0 0 0"/>
  </xacro:new_box>

   <!-- wall long side -->
  <xacro:new_box new_box_name="wall_long_2" box_width ="0.1" box_length="4" box_height="0.5" material="experiments/wall" parent="world">
  <origin xyz="3 -2.05 -0.05" rpy="0 0 0"/>
  </xacro:new_box>


  <!-- wood floor rectangle link -->
  <xacro:new_box new_box_name="wood_floor_rectangle_2" box_width ="1" box_length="4" box_height="0.1" material="experiments/woodfloor" parent="world">
  <origin xyz="3 -1.5 -0.05" rpy="0 0 0"/>
  </xacro:new_box>


  <!-- cameras  -->
  <xacro:camera_sensor xyz="5 2 1.5" rpy="0 0 0" parent="world" camera_suffix="right"/>
  <xacro:camera_sensor xyz="10 0 1.5" rpy="0 0 0" parent="world" camera_suffix="end"/>

  <!-- <link name="threshold">
    <xacro:box_inertial x="2" y="0.09" z="0.1" mass="2">
	   <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:box_inertial>
      <visual>
        <origin xyz="0 0 0.0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://araig_gazebo_worlds/media/models/threshold.dae" scale="1 1 1"/>
        </geometry>
      </visual>
  </link>
  <gazebo reference="threshold">
    <static>true</static>
  </gazebo>
  <joint name="joint_threshold" type="fixed">
    <origin xyz="3 1 0" rpy="0 0 0" />
    <parent link="box_normal_floor" />
    <child link="threshold" />
  </joint> -->
  <transmission name="belt_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="floor_to_belt">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="belt_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</robot>
