<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
	name="obstacle">  

  <xacro:macro name="default_inertial">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </xacro:macro>


  <xacro:macro name="new_cylinder" params="new_cylinder_name cylinder_diameter cylinder_height material parent *origin">
    <link name="cylinder_${new_cylinder_name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
              <cylinder length="${cylinder_height}" radius="${cylinder_diameter/2}"/>
        </geometry>
      </visual>
      <!-- <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
  	  <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </collision> -->
      <xacro:default_inertial/>
    </link>
    <gazebo reference="cylinder_${new_cylinder_name}">
      <material>${material}</material>
    </gazebo>
    <joint name="joint_box_${new_cylinder_name}" type="fixed">
       <xacro:insert_block name="origin"/>
       <parent link="${parent}"/>
       <child link="cylinder_${new_cylinder_name}"/>
    </joint>
  </xacro:macro>


  <!-- world link -->
  <link name="world" />



  <!-- cylinder link -->
  <xacro:new_cylinder new_cylinder_name="static_obstacle_1" cylinder_diameter = "0.2" cylinder_height = "1" material="experiments/wall" parent="world">
  <origin xyz="3 0 -0.2" rpy="0 0 0"/>
  </xacro:new_cylinder>

</robot>

